== Determine what Kernel Live Patches are available

When Kernel Live Patches are applied to the kernel, functions within the
kernel are re-routed from their initial instructions to instead use the
functions provided by the kpatch. The following diagram provides a bit
more detail on how this process operates.

This means that a kpatch is produced and tied to a specific version of
the kernel. Before you look at available kernel patches, you should
first know the version of the kernel running on your target system.

[source,bash,run]
----
uname -r
----

Our lab system is running kernel version (also known as release, hence
the -r option used by uname) kpatch-patch-5_14_0-427_31_1.x86_64.

Now that you know the version of the kernel running on the lab machine,
look at all of the aviailable kpatch packages avaiable from the Red Hat
Enterprise Linux repos.

[source,bash,run]
----
dnf list available kpatch-patch-*427_31_1.x86_64
----

From the above output, there are several different kpatch-patch patches
available, but only one of them is the one intended for the kernel
running on your system. The one needed for your system is
`+kpatch-patch-5_14_0-427_31_1.x86_64+` because it is the latest
available for the version of your kernel reported by `+uname -r+`,
specifically, 5.14.0-427.13.1.el9_4.x86_64.

If you looked at all available `+kpatch-patch+` packages, you would see
others listed, like `+kpatch-patch-5_14_0-427_31_1.x86_64+`. 

[source,bash,run]
----
dnf list available kpatch-patch*
----

These kpatches are for another kernel, specifically, version 5.14.0-162. You
can see that the additional listings are also for addtional kernel
releases, *not* the one running on your system.

In the next step, you will be applying the kpatch available for your
system to the kernel.
